title: "いま、PowerShellをはじめよう ～Begin The PowerShell～"
summary: |-
  そろそろバッチファイル（*.bat）ではなくPowerShellで自動化してみませんか。
  
  この本はPowerShellを始める為に必要な “セットアップ手順”と “基本的な実践方法”を解説しています。
  
  主に下記の内容が盛り込まれています。
  
  　📌 PowerShellで実現できること
  　📌 PowerShellの導入方法 と 開発環境の構築手順
  　📌 コマンドレット・自作Function・PowerShellスクリプト、3つの活用方法
  
  チャプター7「応用技術の実践」以降を有料として販売しています。
  
  この有料チャプターの内容は、私がZennの個別記事で無料公開している内容を紹介しているのみで、
  無料ですべて閲覧したい方は、この本をご購入いただく必要はありません。
  
  また、Zenn CLIによりコンテンツを連携しているGitHubのリポジトリも公開状態（Public）となっていますので、
  リポジトリを直接のぞいていただければ閲覧可能です。
  
  なお、この公開状態としているGitHubのリポジトリですが、今後の運用方針によって変更する可能性があります。その点、ご了解いただければと思います。
  
  🔖 無料公開している個別記事
  https://zenn.dev/haretokidoki?tab=articles
  
  🔖 この本のGitHubリポジトリの参照先
  https://github.com/akiGAMEBOY/haretokidoki_zn/tree/master/books/b7db6f890d3bf9
  
  それでは、「Chapter 01: はじめに」もしくは「気になるチャプター」のリンクをクリックして本書を読んでいきましょう。

topics: ["powershell", "windows", "mac", "linux"]
published: false
price: 500 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
# chapters:
  # - introduction
  # - basic-knowledge
  # - installation_construction
  # - basic-practice
  # - community_contact
  # - references
  # - applied-practice
  # - conclusion
toc_depth: 3