title: "いまからPowerShellをはじめましょう ～ Begin The PowerShell ～ "
summary: |-
  この本はPowerShellを始める為に必要な “セットアップ手順”と “基本的な実践方法”を解説しています。
  
  主に下記の内容が盛り込まれています。
  　📌PowerShellで実現できること
  　📌PowerShellの導入方法 と 開発環境の構築手順
  　📌コマンド・自作Function・スクリプトの活用方法
topics: ["powershell", "windows", "mac", "linux"]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - introduction
  - basic-knowledge
  - installation_construction
  - basic-practice
  - applied-practice
  - community_contact
  - references
  - conclusion
toc_depth: 3